name: OSX-SDL2-Brew-2
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install Financials Dependencies
      run: |
        brew install cmake libx11 libxi libxrandr libxxf86vm pkg-config mesa sdl2 freeglut openal-soft
    - name: Compile
      run: |
        cd src
        make -f Makefile
    - name: Create tarball
      run: |
          tar -cvf fixGB.tgz fixGB
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: |
          ./fixGB.tgz
